In [1]:
#넘파이 수치데이터, 벡터 및 행렬 사용하는 선형 대수 계산에서 많이 사용.
!pip install numpy 

In [2]:
import numpy as np

In [4]:
np_array_1 = np.array([1, 2, 3, 4])
print(np_array_1)
print(type(np_array_1))

[1 2 3 4]
<class 'numpy.ndarray'>


해당 형태가 array 형태

In [8]:
np_array_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(np_array_2)

[[1 2 3]
 [4 5 6]]


In [9]:
#array 행의 수를 출력
np_array_2.ndim

2

In [10]:
#array의 크기를 출력
np_array_2.shape

(2, 3)

In [11]:
# 0행렬
zero_array = np.zeros((3, 4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
# 1로 채워진 행렬
one_array = np.ones((3, 3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
full_array = np.full((4, 4), 3) #여기 3대신에 0 넣으면 0행렬 됨
print(full_array)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [16]:
#단위행렬
eye_array = np.eye(5) #크기를 하나로 적어주면 됨
print(eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
#랜덤
random_array = np.random.random((3, 3))
print(random_array)

[[0.26003718 0.02546766 0.06289443]
 [0.23132364 0.72636545 0.02828153]
 [0.93945848 0.0844715  0.35565439]]


In [20]:
arange_array = np.arange(10) #10개의 개수, 크기가 하나인데, 크기를 변경해주는 함수도 있다.
print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
reshape_array = arange_array.reshape(2, 5) #원소의 값은 그대로인데 크기가 변경된다.
print(reshape_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
# 행렬 연산
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [24]:
# 행렬의 합
print(x + y)
print(np.add(x, y))

[5 7 9]
[5 7 9]


In [25]:
# 행렬의 차
print(x - y)
print(np.subtract(x, y))

[-3 -3 -3]
[-3 -3 -3]


In [27]:
# 행렬의 곱
print(x * y)
print(np.multiply(x, y))

[ 4 10 18]
[ 4 10 18]


In [31]:
# 행렬의 나누기
print(x / y)
print(np.divide(x, y))

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [32]:
# 행렬의 행렬곱
x2 = np.array([[1, 2], [3, 4]])
y2 = np.array([[5, 6], [7, 8]])

In [33]:
print(x2 @ y2)
print(np.dot(x2, y2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
